package models

type GasSteps struct {
	PriceCoef                  float64 `json:"price_coef"`
	CompanyID                  int     `json:"company_id"`
	Username                   string  `json:"username"`
	Currency                   string  `json:"currency"`
	InflationUSD               float64 `json:"inflation_usd"`
	ExchangeRate               float64 `json:"exchange_rate"`
	ID                         int     `json:"id"`
	KPN                        float64 `json:"kpn"`
	Year                       int     `json:"year"`
	InflationKZT               float64 `json:"inflation_kzt"`
	PriceExport                float64 `json:"price_export"`
	PriceDomestic              float64 `json:"price_domestic"`
	GasSalesExport             float64 `json:"gas_sales_export"`
	GasSalesExportLastYear     float64 `json:"gas_sales_export_last_year"`
	GasSalesDomestic           float64 `json:"gas_sales_domestic"`
	GasSalesDomesticLastYear   float64 `json:"gas_sales_domestic_last_year"`
	RevenueGasExport           float64 `json:"revenue_gas_export"`
	RevenueGasDomestic         float64 `json:"revenue_gas_domestic"`
	VolumeGasTransport         float64 `json:"volume_gas_transport"`
	TariffGasTransport         float64 `json:"tariff_gas_transport"`
	SpecificTransportCost      float64 `json:"specific_transport_cost"`
	AmortizationRate           float64 `json:"amortization_rate"`
	FinancialIncomeRate        float64 `json:"financial_income_rate"`
	FinancialExpensesRate      float64 `json:"financial_expenses_rate"`
	SpecificKVL                float64 `json:"specific_kvl"`
	OtherSubsidiries           float64 `json:"other_subsidiries"`
	TariffTransportService     float64 `json:"tariff_transport_service"`
	ManagementFee              float64 `json:"management_fee"`
	PurchaseCost               float64 `json:"purchase_cost"`
	Salaries                   float64 `json:"salaries"`
	OtherCosts                 float64 `json:"other_costs"`
	RevenueGasTransport        float64 `json:"revenue_gas_transport"`
	RevenueServiceAndOther     float64 `json:"revenue_service_and_other"`
	RevenueOther               float64 `json:"revenue_other"`
	RevenueTotal               float64 `json:"revenue_total"`
	VolumeProductionKZ         float64 `json:"volume_production_kz"`
	VolumeProductionKZLastYear float64 `json:"volume_production_kz_last_year"`
	ChangeProduction           float64 `json:"change_production"`
	KVL                        float64 `json:"kvl"`
	TransportCost              float64 `json:"transport_cost"`
	CostSoldGas                float64 `json:"cost_sold_gas"`
	PPE                        float64 `json:"ppe"`
	DepreciationAmortization   float64 `json:"depreciation_amortization"`
	TotalCosts                 float64 `json:"total_costs"`
	Loans                      float64 `json:"loans"`
	Cash                       float64 `json:"cash"`
	FinancialExpenses          float64 `json:"financial_expenses"`
	FinancialIncome            float64 `json:"financial_income"`
	OtherIncomeExpenses        float64 `json:"other_income_expenses"`
	TotalIncomeExpenses        float64 `json:"total_income_expenses"`
	TransportedAG              float64 `json:"transported_ag"`
	TransportedGBSH            float64 `json:"transported_gbsh"`
	SpecificNetIncomeAG        float64 `json:"specific_net_income_ag"`
	SpecificNetIncomeGBSH      float64 `json:"specific_net_income_gbsh"`
	NetIncomeAG                float64 `json:"net_income_ag"`
	NetIncomeGBSH              float64 `json:"net_income_gbsh"`
	QGShare                    float64 `json:"qg_share"`
	EBIT                       float64 `json:"ebit"`
	KPNTotal                   float64 `json:"kpn_total"`
	NSP                        float64 `json:"nsp"`
	NetIncome                  float64 `json:"net_income"`
	SpecificNetIncome          float64 `json:"specific_net_income"`
	FCF                        float64 `json:"fcf"`
	SpecificFCF                float64 `json:"specific_fcf"`
	ChangeSalesExport          float64 `json:"change_sales_export"`
	ChangeSalesDomestic        float64 `json:"change_sales_domestic"`
	DiscountPeriod             int     `json:"discount_period"`
	DiscountRate               float64 `json:"discount_rate"`
	DCF                        float64 `json:"dcf"`
	CashNew                    float64 `json:"cash_new"`
	LoansNew                   float64 `json:"loans_new"`
}
